kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048M

archives_base_name=WorldTools
maven_group=org.waste.of.time
mod_version=1.2.9

minecraft_version=1.21.5
enabled_platforms=fabric,forge
architectury_version=15.0.1
mixinextras_version=0.4.1
cloth_config_version=17.0.144
mod_menu_version=13.0.0

# Fabric https://fabricmc.net/develop/
fabric_loader_version=0.16.10
yarn_mappings=1.21.5+build.1
fabric_api_version=0.126.0+1.21.5
fabric_kotlin_version=1.13.3+kotlin.2.1.21

# Forge
forge_version=1.21.5-55.0.22
kotlin_forge_version=5.8.0
